apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: traefik

spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: admin
      port: 8080
      nodePort: 38080
    - protocol: TCP
      name: websecure
      port: 443
  selector:
    app: traefik
